name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  checks:
    strategy:
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.7
    with:
      format-check: ${{ matrix.sdk == '2.19.6' || true && false }}

  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.7

  unit-tests:
    strategy:
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    uses: Workiva/gha-dart-oss/.github/workflows/test-unit.yaml@v0.1.7